name: "CI"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            nix-devenv: ./**/nix-devenv/**
  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ needs.detect-changes.outputs != '[]' }}

    steps:
      - uses: actions/checkout@v4
      - run:  ${{ needs.detect-changes.outputs }}
      # - name: Smoke test for '${{ matrix.templates }}'
      #   id: smoke_test
      #   uses: ./.github/actions/smoke-test
      #   with:
      #     template: "${{ matrix.templates }}"
