name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
permissions:
   contents: read
   issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: brpaz/action-label-syncer@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml